admin/object.php
core/tpl/admin/object/object_const_view.tpl.php
core/tpl/admin/object/object_numbering_module_view.tpl.php

#225 [Admin] add: template admin object

---

core/modules/saturne/modules_saturne.php

#226 [Mod] add: ModeleNumRefSaturne class for manage all modRef

---

admin/about.php
lib/saturne.lib.php

#227 [Admin] add: about page rework

---

class/saturneobject.class.php

#98 [SaturneObject] add: generic object extend commonObject

---

class/saturneobject.class.php
class/saturneschedules.class.php
class/saturnesignature.class.php
lib/saturne_functions.lib.php

#197 [Mod] add: use isModEnabled function instead of $conf

---

class/saturnedocuments.class.php
sql/documents/index.php
sql/documents/llx_saturne_object_documents.key.sql
sql/documents/llx_saturne_object_documents.sql

[SaturneDocuments] add: object documents for saturne

---

admin/documents.php
core/tpl/admin/object/object_document_model_view.tpl.php

[Admin] add: documents page for manage module documents

---

saturne_dev.md

#118 [Doc] add: improve documentation dev for use saturne

---

lib/saturne_functions.lib.php

#251 [Lib] add: banner tab projectid key check

---

langs/en_US/object.lang
langs/fr_FR/object.lang

#249 [Trad] add: rename right trad for prevent conflict with formconfirm trad

---

class/saturnecertificate.class.php
class/saturnedocuments.class.php
class/saturnesignature.class.php
public/signature/add_signature.php

#253 [Signature] add: builddoc action for specimen public interface

---

core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
lib/object.lib.php
view/saturne_attendants.php

#276 [SaturneAttendants] add: moreparam attendant_table_mode manage display mode attendants

---

core/modules/saturne/modules_saturne.php

#279 [Mod] fix: fatal cause typage function need object instead of commonObject

---

admin/object.php

#269 [Config] add: setup logo

---

lib/medias.lib.php

#241 [Lib] fix: move check in end of foreach

---

class/saturnecertificate.class.php
sql/certificate/llx_saturne_object_certificate.sql

#287 [SaturneCertificate] add: missing field type

---

admin/object.php
core/tpl/admin/object/object_extrafields_view.tpl.php
langs/en_US/saturne.lang
langs/fr_FR/saturne.lang

#294 [Admin] add: tpl admin object extrafields management

---

admin/documents.php

#306 [Admin] fix: do generic call instead of module functions call

---

langs/en_US/saturne.lang
langs/fr_FR/saturne.lang

#300 [Translation] add: config 

---

public/signature/add_signature.php

#316 [PublicInterface] add: change directory for specimen

---

core/tpl/object/object_action_workflow.tpl.php

#315 [TPL] add: confirm action TPL

---

core/modules/saturne/modules_saturne.php

#314 [ODT] Rework doc write file generation

---

core/tpl/admin/object/object_extrafields_view.tpl.php
langs/en_US/saturne.lang
langs/fr_FR/saturne.lang

#325 [TPL] add: extrafields TPL

---

README.md
core/modules/modSaturne.class.php

#328 [Mod] add: new version number 1.1.0

---

lib/documents.lib.php

#330 [Lib] fix: change value trunc template name

---

sql/update.sql

#332 [SQL] add: backward SQL signature and documents

---

langs/en_US/signature.lang
langs/fr_FR/signature.lang
view/saturne_attendants.php

#348 [Trad] fix: missing trad variable

---

langs/en_US/medias.lang
langs/en_US/object.lang
langs/fr_FR/medias.lang
langs/fr_FR/object.lang

#352 [Trad] add: generic trad medias/object

---

class/saturneobject.class.php

#378 [SaturneObject] fix: typing error

---

admin/about.php
admin/documents.php
admin/media_gallery.php
admin/setup.php
core/tpl/admin/object/object_const_view.tpl.php
langs/en_US/medias.lang
langs/en_US/saturne.lang
langs/fr_FR/medias.lang
langs/fr_FR/saturne.lang

#379 [Admin] add: improve admin document for manage medias and const

---

core/tpl/attendants/attendants_table_add_view.tpl.php
core/tpl/attendants/attendants_table_view.tpl.php
view/saturne_attendants.php

#370 [SaturneAttendants] fix: empty value need to be array signatoriesByRole

---

view/saturne_note.php

#384 [SaturneNote] add: check object status for manage permissionnote

---

class/saturnedashboard.class.php

#385 [SaturneDashboard] add: list management

---

lib/saturne_functions.lib.php

#386 [Lib] fix: missing check label value saturne_banner_tab

---

lib/saturne_functions.lib.php

#387 [Lib] fix: saturne_select_dictionary selected value

---

core/tpl/medias/medias_gallery_modal.tpl.php

#388 [Lib] fix: creation media with id 0

---

core/tpl/attendants/attendants_table_view.tpl.php
public/signature/add_signature.php
view/saturne_attendants.php

#402 [SaturneAttendants] fix: display date tzuser and save in UTC

---

admin/documents.php

#404 [adminConf] add: change value conf for DOCUMENT_MEDIA_VIGNETTE_USED

---

core/tpl/attendants/attendants_table_add_view.tpl.php
core/tpl/attendants/attendants_table_view.tpl.php
view/saturne_attendants.php

#405 [SaturneAttendants] fix: missing parameters in url

---

core/modules/saturne/modules_saturne.php
core/tpl/documents/documents_action.tpl.php

#419 [TPL] add: conf check defined and wrong variable name and check global value

---

class/saturnedashboard.class.php

#438 [SaturneDashboard] fix: remove info-box-sm css error

---

sql/update.sql

#372 [SQL] fix: missing update field attendance signature

---

core/tpl/attendants/attendants_table_view.tpl.php

#430 [Attendants] fix: disable send mail if signature not null

---

lib/saturne_functions.lib.php

#422 [Lib] fix: saturneBannerTab show all projects

---

langs/en_US/saturne.lang
langs/en_US/signature.lang
langs/fr_FR/saturne.lang
langs/fr_FR/signature.lang

#552 [Trad] add: signatory trad

---

public/signature/add_signature.php

#572 [PublicSignature] add: check document_type variable and file exists

---

lib/medias.lib.php

Return media linked element count

#594 [Media] add: saturne_get_media_linked_element function

---

class/saturneredirection.class.php

fix: #1165

---

class/saturneobject.class.php

- Allow to call method with 4 given arguments
- Force to use given arguments in query (instead of id/type of current object)

SaturneObject add deleteObjectLinked method to override commonobject one
